### ISSUE TITLE
Restructure: Rename to dotnet-execute and rewrite for packit

### ISSUE THREAD

**Issue by joshzarrabi** [paketo-buildpacks/dotnet-execute#77] opened 2020-09-14 18:40 UTC
### Background

This buildpack executes `dll` files built by the `dotnet publish` command by running `dotnet <app>.dll`
It is confusing that it is named `dotnet-core-conf`, as it is not as all descriptive of what the buildpack does.

### Proposal

In order to conform the the [restructure rfc](https://github.com/paketo-buildpacks/dotnet-core/blob/main/rfcs/0001-restructure.md), this buildpack should

* Be rewritten to be `packit` compliant
* Be renamed to `dotnet-execute` as that is a more descriptive name.

For now we should keep all functionality the same.

### Note:

Make sure to go through the rest of the README's in the language family and change the references to theis buildpack to be correct.

**Comment by kvedurmu** [comment] 2020-10-14 21:43
Reopening this. Looks like the .NET Execute always requires the ICU dependency. ICU should only be required on the Base stack. You can replicate this by building a self contained app on the full stack
```
pack build dotnet-execute-app --buildpack ~/Downloads/dotnet-core-0.0.9.cnb
full: Pulling from paketobuildpacks/builder
Digest: sha256:4dc98cdfd4ebd5811ee50029695d25a5ddbcdfb912ceecbdf364019bd8ddbd16
Status: Image is up to date for paketobuildpacks/builder:full
full-cnb: Pulling from paketobuildpacks/run
Digest: sha256:fca60d5476d5a7dc75deb3c8dad59514994958b4d267160f238e120bf8d79dc7
Status: Image is up to date for paketobuildpacks/run:full-cnb
===> DETECTING
2 of 7 buildpacks participating
paketo-buildpacks/icu            0.0.97
paketo-buildpacks/dotnet-execute 0.0.179
===> ANALYZING
Previous image with name "dotnet-execute-app" not found
===> RESTORING
===> BUILDING

ICU Buildpack 0.0.97
   67.1.0: Contributing to layer
    Downloading from https://buildpacks.cloudfoundry.org/dependencies/icu/icu_67.1.0_linux_noarch_any-stack_00267b03.tgz
    Verifying checksum
    Expanding to /layers/paketo-buildpacks_icu/icu
Paketo .NET Execute Buildpack 0.0.179
  Assigning launch processes
    web: ./asp_dotnet2 --urls http://0.0.0.0:${PORT:-8080}
```

**Comment by arjun024** [comment] 2020-10-15 13:55
@kvedurmu I believe this is by design. Is that right @floragj @ForestEckhardt?
Before the rewrite, icu was "required" for both [full and bionic stacks](https://github.com/paketo-buildpacks/dotnet-execute/blob/v0.0.177/cmd/detect/main.go#L64-L69) (they both have the same stack id). I think what we should do is remove (the soon to be deprecated) cflinuxfs3 stack from the list of supported stacks in the buildpack.toml.

**Comment by kvedurmu** [comment] 2020-10-15 14:27
Hmm, I think we should still get this fixed here. The Full stack (io.buildpacks.stacks.bionic ID + mixins) already has the ICU dependency, so we should not be requiring the buildpack. See the list of packages installed in the Full stack - https://github.com/paketo-buildpacks/stacks/tree/main/packages/full

**Comment by kvedurmu** [comment] 2020-10-15 18:28
Nevermind, after some discussion we decided that this is by design. Since the Stack ID for both the Full and Bionic stacks now have the same ID, we have no way of determining whether the stack is Full without digging through OS packages. This buildpack works as expected. Built a self contained app and confirmed that it prints packit style log output. We can close this.

**Closed by kvedurmu** 2020-10-15 18:28 UTC
